In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

In [ ]:
df = pd.read_csv(r'/content/Churn_Modelling.csv')
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [ ]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [ ]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(x))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#intializing ANN
ann = tf.keras.models.Sequential()

In [ ]:
#adding input layer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

In [ ]:
#addding another hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

In [ ]:
#adding output layer
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [ ]:
#training ANN
#compiling ANN
ann.compile(optimizer='adam' ,loss='binary_crossentropy',metrics=['accuracy'])#loss will be categorical_crossentropy in case of more than 2 classes
ann.fit(X_train,y_train,batch_size = 32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.3321 - accuracy: 0.8690
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8681
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3469 - accuracy: 0.8609
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8716
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3357 - accuracy: 0.8633
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3390 - accuracy: 0.8625
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3316 - accuracy: 0.8646
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3361 - accuracy: 0.8649
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3309 - accuracy: 0.8654
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3318 - accura

In [ ]:
#predictions
ANN = ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))
print(ANN>0.5)
print(ANN)

[[False]]
[[0.03808632]]


In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
ac = accuracy_score(y_test,y_pred)
print(cm)
print(ac*100,"%")

[[1520   75]
 [ 204  201]]
86.05000000000001 %
