In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv(r'/content/Ensemble.csv - Ensemble.csv.csv')
print(df)

    Height (in cms)  Weight (in kgs) T Shirt Size
0             158.0             58.0            M
1             158.0             59.0            M
2             158.0             63.0            M
3             160.0             59.0            M
4             160.0             60.0            M
5             189.0              NaN            M
6             100.0             67.0          NaN
7             168.0             66.0            L
8             170.0             63.0            L
9             170.0             64.0            L
10            200.0              NaN            M
11            210.0             89.0          NaN
12            163.0             60.0            M
13            163.0             61.0            M
14            160.0             64.0            L
15            163.0             64.0            L
16            165.0             61.0            L
17            163.0              NaN          NaN
18            165.0             61.0          NaN


In [ ]:
df.shape

(29, 3)

In [ ]:
df1 = df.dropna()

In [ ]:
print(df1)

    Height (in cms)  Weight (in kgs) T Shirt Size
0             158.0             58.0            M
1             158.0             59.0            M
2             158.0             63.0            M
3             160.0             59.0            M
4             160.0             60.0            M
7             168.0             66.0            L
8             170.0             63.0            L
9             170.0             64.0            L
12            163.0             60.0            M
13            163.0             61.0            M
14            160.0             64.0            L
15            163.0             64.0            L
16            165.0             61.0            L
21            165.0             62.0            L
22            165.0             65.0            L
23            168.0             62.0            L
24            168.0             63.0            L
28            170.0             68.0            L


In [ ]:
df2 = df.fillna(method='ffill')
print(df2)

    Height (in cms)  Weight (in kgs) T Shirt Size
0             158.0             58.0            M
1             158.0             59.0            M
2             158.0             63.0            M
3             160.0             59.0            M
4             160.0             60.0            M
5             189.0             60.0            M
6             100.0             67.0            M
7             168.0             66.0            L
8             170.0             63.0            L
9             170.0             64.0            L
10            200.0             64.0            M
11            210.0             89.0            M
12            163.0             60.0            M
13            163.0             61.0            M
14            160.0             64.0            L
15            163.0             64.0            L
16            165.0             61.0            L
17            163.0             61.0            L
18            165.0             61.0            L


In [ ]:
x = df2.iloc[:,0:2].values
y = df2.iloc[:,2].values
print(x)
print(y)

[[158.  58.]
 [158.  59.]
 [158.  63.]
 [160.  59.]
 [160.  60.]
 [189.  60.]
 [100.  67.]
 [168.  66.]
 [170.  63.]
 [170.  64.]
 [200.  64.]
 [210.  89.]
 [163.  60.]
 [163.  61.]
 [160.  64.]
 [163.  64.]
 [165.  61.]
 [163.  61.]
 [165.  61.]
 [165.  64.]
 [168.  64.]
 [165.  62.]
 [165.  65.]
 [168.  62.]
 [168.  63.]
 [168.  67.]
 [210.  67.]
 [210.  89.]
 [170.  68.]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'L' 'L' 'L' 'M' 'M' 'M' 'M' 'L' 'L' 'L' 'L'
 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'M' 'L' 'L']


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_new = le.fit_transform(y)
y = y_new
print(y_new)

[1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20,random_state= 0)

In [ ]:
x_train.shape
x_test.shape

(6, 2)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model1 = DecisionTreeClassifier(max_depth=5)
model2 = LogisticRegression()
model3 = SVC(kernel='rbf')
model4 = KNeighborsClassifier(n_neighbors=6,metric='euclidean')

In [ ]:
model1.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
model2.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
model3.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
model4.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [ ]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)
y_pred4 = model4.predict(x_test)

In [ ]:
print(y_pred1)
print(y_pred2)
print(y_pred3)
print(y_pred4)

[0 0 0 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 0 0]
[1 0 0 0 0 0]


In [ ]:
from sklearn.metrics import accuracy_score
dt_acc = accuracy_score(y_test,y_pred1)
print(dt_acc*100,'%')

50.0 %


In [ ]:
from sklearn.metrics import accuracy_score
log_acc = accuracy_score(y_test,y_pred2)
print(log_acc*100,'%')

66.66666666666666 %


In [ ]:
from sklearn.metrics import accuracy_score
sv_acc = accuracy_score(y_test,y_pred3)
print(sv_acc*100,'%')

50.0 %


In [ ]:
from sklearn.metrics import accuracy_score
knn_acc = accuracy_score(y_test,y_pred4)
print(knn_acc*100,'%')

66.66666666666666 %


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 120,criterion='entropy',max_depth = 10)

In [ ]:
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=120,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred5 = rfc.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
rfc_score = accuracy_score(y_test,y_pred5)
print(rfc_score*100,'%')

50.0 %


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators = 120,base_estimator = None,learning_rate = 1,random_state = 1)

In [ ]:
abc.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1,
                   n_estimators=120, random_state=1)

In [ ]:
y_pred6 = abc.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
abc_score = accuracy_score(y_test,y_pred6)
print(abc_score*100,'%')

50.0 %
